name: authentication
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  dio: ^5.3.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  dartz: ^0.10.1
  injectable: ^2.3.2
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
